name = "lehn-dev-homepage-v2"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "."          # serve everything in the repo root
exclude = ["worker", "node_modules", ".github", "*.md", "*.toml"]
